name: CI test.

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup python  3.11.2
        uses: actions/setup-python@v1
        with:
          python-version: 3.11.2
      - name: Install dependencies
        run: |
          make install
      - name: get the requirements
        run: |
          make get-requirements
